package org.hsu.hsuapp.util.taba;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import org.hsu.hsuapp.util.FileUtil;
import org.hsu.hsuapp.util.StringUtil;

public class AutoGenTrans {

	private static String GAME_PATH = "D:\\taba";
	private static String AUTO_GEN_TRANS_TXT = "_AutoGeneratedTranslations.txt";
	private String charsetName = "UTF-8";
	
	private List<String[]> autoGenTransList = new ArrayList<String[]>(); // 暫存已翻譯的資料

	public AutoGenTrans(String path) {
		this.GAME_PATH = path;
	}

	/**
	 * 讀取-已翻譯的資料
	 */
	public void load() {
		File f = new File(GAME_PATH, AUTO_GEN_TRANS_TXT);
		List<String> list = FileUtil.readFileToList(f.getAbsolutePath(), charsetName);
		for (String row : list) {
			String[] datas = row.split("=");
			if (datas.length > 1)
				autoGenTransList.add(datas);
		}
	}
	
	/**
	 * 查詢-已翻譯的資料
	 * 
	 * @param q
	 * @return
	 */
	public String query(String q) {
		String r = "";
		for (String[] data : autoGenTransList) {
			if (data.length > 1) {
				String from = data[0];
				if (q.equals(from))
					r = data[1];
			}
		}
		return r;
	}
	
	/**
	 * 寫入新的翻譯資料
	 * 
	 * @param from
	 * @param to
	 */
	public void write(String from, String to) {
		if ((!StringUtil.isBlank(from) || !StringUtil.isBlank(to))) {
			System.out.println("write autoGenTransList and File...");
			// 暫存
			autoGenTransList.add(new String[] { from, to });
			// 寫檔
			String data = from + "=" + to + "\r\n";
			File f = new File(GAME_PATH, AUTO_GEN_TRANS_TXT);
			FileUtil.writeFile(f.getAbsolutePath(), data, true);
		}
	}
	
	public List<String[]> getAutoGenTransList() {
		return autoGenTransList;
	}

	public static void main(String[] args) {
		String GAME_PATH = "D:\\taba";
		AutoGenTrans autoGenTrans = new AutoGenTrans(GAME_PATH);
		autoGenTrans.load();
		
		List<String[]> autoGenTransList = autoGenTrans.getAutoGenTransList();
//		for (String[] data : autoGenTransList) {
//			System.out.println(data[0] + "==" + data[1]);
//		}
		String q = "キスで気持ちを表す";
		System.out.println(q);
		String trans = autoGenTrans.query(q);
		System.out.println("TRANS=" + trans);

		if (StringUtil.isBlank(trans)) {
			String from = "キスで気持ちを表す";
			String to = "用一個吻表達你的感受";
			autoGenTrans.write(from, to);
		}

		System.out.println(q);
		System.out.println("TRANS=" + autoGenTrans.query(q));		
		
	}
}
